Repository cboard-org/cboard, pull requests merged in 2022-12, with the labels that each got.

#1301 Side navigation buttons
  src/components/App/App.reducer.js
  src/components/App/__tests__/App.reducer.test.js
  src/components/Board/Board.component.js
  src/components/Board/Board.css
  src/components/EditGridButtons/EditGridButtons.component.js
  src/components/EditGridButtons/EditGridButtons.css
  src/components/FixedGrid/Grid.js
  src/components/Grid/Grid.css
  src/components/NavigationButtons/NavigationButtons.component.js
  src/components/NavigationButtons/NavigationButtons.css
  src/components/ScrollButtons/ScrollButtons.js
  src/components/Settings/Navigation/Navigation.component.js
  src/components/Settings/Navigation/Navigation.constants.js
  src/components/Settings/Navigation/Navigation.messages.js
  src/components/Settings/Navigation/Navigation.test.js
  src/components/Settings/Navigation/__snapshots__/Navigation.test.js.snap
  src/translations/src/cboard.json
Labels: feature, Ceibal

#1314 Relative position for scroll buttons
  src/components/Board/Board.component.js
  src/components/Board/Board.css
  src/components/NavigationButtons/NavigationButtons.component.js
  src/components/NavigationButtons/NavigationButtons.css
  src/components/ScrollButtons/ScrollButtons.js
Labels: bug

#1321 ARASAAC scripts to get symbols and data
  scripts/arasaac-create-files.js
  scripts/arasaac-download-symbols.js
Labels: feature, Ceibal

#1176 Correct differentiation between local and cloud voices
  src/providers/SpeechProvider/SpeechProvider.actions.js
  src/providers/SpeechProvider/tts.js
Labels: bug

#1325 Feature / Show tour on first login
  src/components/Account/Login/Login.actions.js
  src/components/Account/Login/Login.actions.test.js
Labels: feature, Ceibal

#1328 Decrease the maxWidth for the DefaultBoardSelector Dialog
  src/components/Communicator/CommunicatorToolbar/DefaultBoardSelector/DefaultBoardSelector.js
Labels: bug, Ceibal
