Repository cboard-org/cboard, pull requests merged in 2022-11, with the labels that each got.

#1293 Scroll top with back action
  src/components/Board/Board.component.js
  src/components/Board/Board.container.js
  src/components/ScrollButtons/ScrollButtons.js
Labels: Ceibal

#1276 Prevent app crash during cancel speech
  src/providers/SpeechProvider/SpeechProvider.actions.js
Labels: bug

#1270 Show information alert indicating that a cloud voice is seted
  src/components/Notifications/Notifications.component.js
  src/components/Notifications/Notifications.messages.js
  src/providers/SpeechProvider/SpeechProvider.actions.js
  src/translations/src/cboard.json
Labels: feature

#1298 Not show the "cloud voice was set" alert on app init
  src/components/Notifications/Notifications.messages.js
  src/providers/SpeechProvider/SpeechProvider.actions.js
  src/translations/src/cboard.json
Labels: bug

#1266 Improves how offlineVoiceAlert determines if the user's voice is cloud
  src/components/Board/Board.container.js
Labels: feature
