Repository cboard-org/cboard, pull requests merged in 2023-12, with the labels that each got.

#1624 [Snyk] Upgrade pdfmake from 0.2.7 to 0.2.8
  package.json
  yarn.lock
Labels: dependencies

#1623 [Snyk] Upgrade mongoose from 6.12.2 to 6.12.3
  package.json
  yarn.lock
Labels: dependencies

#1619 [Snyk] Upgrade @crowdin/crowdin-api-client from 1.25.1 to 1.26.0
  package.json
  yarn.lock
Labels: dependencies

#1639 Fix - Android Google logout
  src/api/api.js
  src/components/Settings/People/People.container.js
  src/components/Settings/Settings.component.js
  src/components/WelcomeScreen/WelcomeScreen.container.js
  src/constants.js
Labels: bug

#1630 Fix/lost of boards when create a parent board
  src/components/Board/Board.actions.js
  src/components/Board/Board.container.js
  src/components/Board/Board.reducer.js
Labels: bug

#1505 Feature - Add Google Analytics support for Electron platform
  package.json
  src/components/Account/Login/Login.actions.js
  src/components/App/App.container.js
  src/components/Board/Board.analytics.js
  src/constants.js
  src/cordova-util.js
  src/ga4mp.js
  src/providers/SpeechProvider/SpeechProvider.analytics.js
  yarn.lock
Labels: cordova, electron

#1647 Fix the order of params on pdfExportAdapter
  src/components/Settings/Export/Export.helpers.js
Labels: bug

#1655 Fix getSubscriber on paypal approve
  src/components/Settings/Subscribe/Subscribe.container.js
Labels: bug
