Repository cboard-org/cboard, pull requests merged in 2023-05, with the labels that each got.

#1472 Fix android subscription
  src/components/Settings/Subscribe/Subscribe.container.js
  src/components/Settings/Subscribe/Subscribe.messages.js
  src/components/Settings/Subscribe/SubscriptionInfo.js
  src/components/Settings/Subscribe/SubscriptionPlans.js
  src/providers/SubscriptionProvider/SubscriptionProvider.actions.js
  src/providers/SubscriptionProvider/SubscriptionProvider.container.js
  src/translations/src/cboard.json
Labels: premiun

#1481 Fix/search symbol for edit board image
  src/components/Board/SymbolSearch/SymbolSearch.component.js
  src/components/Communicator/CommunicatorDialog/CommunicatorDialogBoardItem.component.js
Labels: bug

#1484 Fix/Android Subscription
  src/api/api.js
  src/components/Settings/Subscribe/Subscribe.container.js
  src/components/Settings/Subscribe/Subscribe.messages.js
  src/cordova-util.js
  src/providers/SubscriptionProvider/SubscriptionProvider.actions.js
  src/providers/SubscriptionProvider/SubscriptionProvider.container.js
  src/translations/src/cboard.json
Labels: android, premiun
