Repository cboard-org/cboard, pull requests merged in 2023-02, with the labels that each got.

#1348 Feature/show trial period ended when open the app
  src/providers/SubscriptionProvider/SubscriptionProvider.actions.js
  src/providers/SubscriptionProvider/SubscriptionProvider.constants.js
  src/providers/SubscriptionProvider/SubscriptionProvider.container.js
  src/providers/SubscriptionProvider/SubscriptionProvider.reducer.js
Labels: premiun

#1349 Unlock premium features if the user isOnTrialPeriod
  src/components/PremiumFeature/PremiumFeature.js
Labels: premiun

#1371 Remove npm CLI commands from README.md
  README.md
  package.json
  public/index.html
Labels: bug

#1369 [Snyk] Upgrade microsoft-cognitiveservices-speech-sdk from 1.22.0 to 1.25.0
  package.json
  yarn.lock
Labels: dependencies

#1367 [Snyk] Upgrade @crowdin/crowdin-api-client from 1.19.0 to 1.21.1
  package.json
  yarn.lock
Labels: dependencies

#1353 Feature/capture premium features
  src/components/Analytics/Analytics.container.js
  src/components/App/App.component.js
  src/components/Board/Board.container.js
  src/components/Board/BoardShare/BoardShare.component.js
  src/components/Board/EditToolbar/EditToolbar.component.js
  src/components/Board/Navbar/Navbar.js
  src/components/Board/Output/PhraseShare/PhraseShare.component.js
  src/components/Board/TileEditor/TileEditor.component.js
  src/components/Communicator/CommunicatorDialog/CommunicatorDialogBoardItem.component.js
  src/components/PremiumFeature/PremiumFeature.js
  src/components/Settings/Export/Export.component.js
  src/components/Settings/Speech/Speech.component.js
Labels: premiun

#1378 Fix/update trial period on unlogged sessions
  src/providers/SubscriptionProvider/SubscriptionProvider.actions.js
  src/providers/SubscriptionProvider/SubscriptionProvider.container.js
Labels: premiun

#1364 Manage empty subscription message on Subscribe component
  src/components/Settings/Subscribe/Subscribe.component.js
  src/components/Settings/Subscribe/Subscribe.constants.js
  src/components/Settings/Subscribe/Subscribe.messages.js
Labels: premiun

#1383 Feature/ Render the subscription setting only on Android and on not subscription-free country
  src/components/Settings/Settings.component.js
  src/components/Settings/Settings.container.js
Labels: premiun

#1387 Remove unnecesary logs
  src/api/api.js
  src/providers/SubscriptionProvider/SubscriptionProvider.actions.js
  src/providers/SubscriptionProvider/SubscriptionProvider.container.js
Labels: premiun
