Repository cboard-org/cboard, pull requests merged in 2023-08, with the labels that each got.

#1560 [Snyk] Upgrade mongoose from 6.11.3 to 6.11.4
  package.json
  yarn.lock
Labels: dependencies

#1559 [Snyk] Upgrade echarts from 5.4.2 to 5.4.3
  package.json
  yarn.lock
Labels: dependencies

#1553 Fix/redirect to login page after activate an account
  src/components/Account/Activate/Activate.actions.js
  src/components/Account/Activate/Activate.container.js
  src/components/Account/Activate/Activate.messages.js
  src/components/Account/Login/Login.actions.js
  src/translations/src/cboard.json
Labels: bug, bug fixing

#1557 Fix/dialogs behind keyboard on Android and IOS
  src/components/Account/Login/Login.component.js
  src/components/Account/SignUp/SignUp.component.js
  src/components/WelcomeScreen/WelcomeScreen.container.js
  src/cordova-util.js
Labels: bug, android, bug fixing

#1555 Fix Text for pdf exported boards
  src/components/Settings/Export/Export.helpers.js
  src/vfs_fonts.js
Labels: bug, bug fixing

#1561 Feature/Redesign exported pdf boards
  src/components/Settings/Export/Export.constants.js
  src/components/Settings/Export/Export.helpers.js
Labels: feature

#1558 Fix/export boards on cordova ios
  src/components/Board/Navbar/Navbar.js
  src/components/Settings/Export/Export.container.js
  src/components/Settings/Export/Export.helpers.js
  src/components/Settings/Export/Export.messages.js
  src/components/Settings/Settings.component.js
  src/cordova-util.js
  src/translations/src/cboard.json
Labels: bug, bug fixing

#1511 Electron - Manage subscription
  src/components/Settings/Settings.component.js
  src/components/Settings/Subscribe/Subscribe.constants.js
  src/components/Settings/Subscribe/SubscriptionInfo.js
  src/components/Settings/Subscribe/SubscriptionPlans.js
Labels: cordova, premiun, electron

#1572 [Snyk] Upgrade microsoft-cognitiveservices-speech-sdk from 1.30.1 to 1.31.0
  package.json
  yarn.lock
Labels: dependencies

#1571 [Snyk] Upgrade @microsoft/applicationinsights-web from 2.8.14 to 2.8.15
  package.json
  yarn.lock
Labels: dependencies

#1566 [Snyk] Upgrade @crowdin/crowdin-api-client from 1.23.4 to 1.24.0
  package.json
  yarn.lock
Labels: dependencies
