Repository cboard-org/cboard, pull requests merged in 2023-11, with the labels that each got.

#1606 [Snyk] Upgrade react-joyride from 2.5.5 to 2.6.0
  package.json
  yarn.lock
Labels: dependencies

#1587 [Snyk] Upgrade @microsoft/applicationinsights-web from 2.8.15 to 2.8.16
  package.json
  yarn.lock
Labels: dependencies

#1600 Use Firebase Plugin to handle google login on Cordova apps
  src/components/WelcomeScreen/WelcomeScreen.container.js
Labels: bug, feature

#1596 Fix/connection setter
  src/components/App/App.actions.js
  src/components/App/App.container.js
  src/store.js
Labels: bug
