Repository cboard-org/cboard, pull requests merged in 2023-03, with the labels that each got.

#1391 Fix on create subscriber
  src/components/Settings/Subscribe/Subscribe.container.js
Labels: premiun

#1395 Fix new IOS devices can't reproduce voice after first speak- Safari IOS and MacOS
  src/providers/SpeechProvider/tts.js
Labels: bug, ios

#1399 Fix/cloud voices on apple
  src/constants.js
  src/providers/SpeechProvider/tts.js
Labels: bug, ios

#1396 Include localhost Web Sockets on Content-Security-Policy to allow Safari development
  public/index.html
Labels: ios

#1406 Fix/Output bar on Ios
  src/components/Board/Output/SymbolOutput/Scroll/Scroll.css
  src/components/Board/Output/SymbolOutput/Scroll/Scroll.js
  src/components/Board/Output/SymbolOutput/SymbolOutput.css
  src/components/Board/Output/SymbolOutput/SymbolOutput.js
Labels: bug, ios

#1402 [Snyk] Upgrade mongoose from 6.9.0 to 6.9.1
  package.json
  yarn.lock
Labels: dependencies

#1400 [Snyk] Upgrade @microsoft/applicationinsights-web from 2.8.5 to 2.8.10
  package.json
  yarn.lock
Labels: dependencies

#1393 Add mediaQuery to PremiumRequiredModal styles
  src/components/PremiumFeature/PremiumRequiredModal.module.css
Labels: premiun

#1428 Premium / Refactor subscribe component
  src/components/Settings/Subscribe/Subscribe.component.js
  src/components/Settings/Subscribe/Subscribe.container.js
  src/components/Settings/Subscribe/SubscriptionPlans.js
Labels: premiun

#1425 [Snyk] Upgrade react-icons from 4.7.1 to 4.8.0
  package.json
  yarn.lock
Labels: dependencies

#1424 [Snyk] Upgrade @crowdin/crowdin-api-client from 1.21.2 to 1.22.0
  package.json
  yarn.lock
Labels: dependencies
