Repository cboard-org/cboard, pull requests merged in 2023-06, with the labels that each got.

#1498 Fix Facebook login on IOS
  src/components/WelcomeScreen/WelcomeScreen.container.js
Labels: bug, ios

#1494 Feature/sign in with apple
  src/api/api.js
  src/components/WelcomeScreen/WelcomeScreen.container.js
  src/components/WelcomeScreen/WelcomeScreen.messages.js
  src/translations/src/cboard.json
Labels: feature, ios

#1496 Feature/delete owned account
  src/api/api.js
  src/components/Settings/People/DeleteConfirmationDialog.js
  src/components/Settings/People/People.component.js
  src/components/Settings/People/People.container.js
  src/components/Settings/People/People.messages.js
  src/components/Settings/Settings.css
  src/translations/src/cboard.json
Labels: feature, ios

#1501 Avoid loop after a 403 response of cboard-api
  src/api/api.js
Labels: bug

#1516 Fix - Avoid loop on getsubscriber request
  src/api/api.js
  src/appInsights.js
  src/components/Settings/Subscribe/Subscribe.container.js
  src/cordova-util.js
  src/index.js
  src/providers/SubscriptionProvider/SubscriptionProvider.actions.js
  src/providers/SubscriptionProvider/SubscriptionProvider.container.js
Labels: bug, premiun
