Repository cboard-org/cboard, pull requests merged in 2023-09, with the labels that each got.

#1585 [Snyk] Upgrade react-icons from 4.10.1 to 4.11.0
  package.json
  yarn.lock
Labels: dependencies

#1583 [Snyk] Upgrade microsoft-cognitiveservices-speech-sdk from 1.31.0 to 1.32.0
  package.json
  yarn.lock
Labels: dependencies

#1573 [Snyk] Security upgrade mongoose from 6.11.5 to 6.12.0
  package.json
  yarn.lock
Labels: dependencies

#1513 Feature/improve phrase
  src/api/api.js
  src/components/App/App.reducer.js
  src/components/App/__tests__/App.reducer.test.js
  src/components/Board/Board.actions.js
  src/components/Board/Board.component.js
  src/components/Board/Board.constants.js
  src/components/Board/Board.container.js
  src/components/Board/Board.reducer.js
  src/components/Board/ImprovePhraseOutput/ImprovePhraseOutput.js
  src/components/Board/ImprovePhraseOutput/ImprovePhraseOutput.module.css
  src/components/Board/ImprovePhraseOutput/index.js
  src/components/Board/Symbol/Symbol.test.js
  src/components/Board/__tests__/Board.actions.test.js
  src/components/Board/__tests__/Board.reducer.test.js
  src/components/Settings/Navigation/Navigation.component.js
  src/components/Settings/Navigation/Navigation.messages.js
  src/components/Settings/Symbols/NoConnectionDialog.js
  src/providers/SubscriptionProvider/SubscriptionProvider.actions.js
  src/translations/src/cboard.json
Labels: feature

#1570 Fix / Export PDF
  src/components/Settings/Export/Export.constants.js
  src/components/Settings/Export/Export.helpers.js
Labels: bug
