Repository cboard-org/cboard, pull requests merged in 2023-07, with the labels that each got.

#1525 Upload audio in mp3 format
  src/components/Board/Board.container.js
Labels: feature

#1523 Fix/play ogg audio on Safari
  package.json
  public/ogv/ogv-decoder-audio-opus-wasm.js
  public/ogv/ogv-decoder-audio-opus-wasm.wasm
  public/ogv/ogv-demuxer-ogg-wasm.js
  public/ogv/ogv-demuxer-ogg-wasm.wasm
  public/ogv/ogv-worker-audio.js
  src/components/Board/Board.container.js
Labels: bug, ios

#1518 [Snyk] Upgrade @microsoft/applicationinsights-web from 2.8.11 to 2.8.14
  package.json
  yarn.lock
Labels: dependencies

#1522 [Snyk] Upgrade microsoft-cognitiveservices-speech-sdk from 1.26.0 to 1.29.0
  package.json
  yarn.lock
Labels: dependencies

#1521 [Snyk] Upgrade @ctrl/react-adsense from 1.5.0 to 1.7.0
  package.json
  yarn.lock
Labels: dependencies

#1520 [Snyk] Upgrade dotenv from 16.0.3 to 16.1.4
  package.json
  yarn.lock
Labels: dependencies

#1519 [Snyk] Upgrade react-social-login-buttons from 3.6.1 to 3.9.1
  package.json
  yarn.lock
Labels: dependencies

#1528 Fix voices.length
  src/components/Settings/Speech/Speech.container.js
Labels: bug

#1536 Fix Text for pdf exported boards
  src/components/Settings/Export/Export.helpers.js
  src/vfs_fonts.js
Labels: bug, bug fixing

#1541 [Snyk] Security upgrade mongoose from 6.10.4 to 6.11.3
  package.json
  yarn.lock
Labels: dependencies

#1540 Prevent linked boards are copied recusively
  src/components/Board/Board.container.js
  src/components/Communicator/CommunicatorDialog/CommunicatorDialog.container.js
Labels: bug, bug fixing

#1544 Fix wrong decoded characters on global symbols suggestions
  src/components/Board/SymbolSearch/SymbolSearch.component.js
Labels: bug, bug fixing

#1535 Feature/Clear Arasaac db
  src/components/Board/SymbolSearch/SymbolSearch.component.js
  src/components/Settings/Symbols/DeleteArasaacDialog.js
  src/components/Settings/Symbols/Symbols.component.js
  src/components/Settings/Symbols/Symbols.container.js
  src/components/Settings/Symbols/Symbols.messages.js
  src/components/UI/Downloader/Downloader.js
  src/idb/arasaac/arasaacdb.ts
  src/translations/src/cboard.json
Labels: bug, bug fixing

#1539 Fix / Get subscriber loop
  src/components/PremiumFeature/PremiumFeature.js
  src/components/Settings/Subscribe/Subscribe.container.js
  src/providers/SubscriptionProvider/SubscriptionProvider.actions.js
  src/providers/SubscriptionProvider/SubscriptionProvider.container.js
  src/providers/SubscriptionProvider/SubscriptionProvider.reducer.js
Labels: bug, bug fixing

#1542 Feature/cordova analytics with firebase
  src/components/Account/Login/Login.actions.js
  src/components/App/App.container.js
  src/cordova-util.js
Labels: bug, bug fixing

#1550 [Snyk] Upgrade react-cropper from 2.3.2 to 2.3.3
  package.json
  yarn.lock
Labels: dependencies

#1549 [Snyk] Upgrade react-joyride from 2.5.3 to 2.5.4
  package.json
  yarn.lock
Labels: dependencies

#1547 [Snyk] Upgrade react-icons from 4.8.0 to 4.10.1
  package.json
  yarn.lock
Labels: dependencies

#1548 [Snyk] Upgrade @crowdin/crowdin-api-client from 1.22.1 to 1.23.2
  package.json
  yarn.lock
Labels: dependencies

#1554 Add a try catch block in every use of FirebasePlugin
  src/components/Account/Login/Login.actions.js
  src/components/App/App.container.js
Labels: bug
