Repository cboard-org/cboard, pull requests merged in 2024-07, with the labels that each got.

#1711 Feature/add only necessary default boards on login
  src/api/communicators.json
  src/components/Account/Login/Login.actions.js
  src/components/Board/Board.actions.js
  src/components/Board/Board.constants.js
  src/components/Board/Board.container.js
  src/components/Board/Board.reducer.js
  src/components/Board/__tests__/Board.actions.test.js
  src/components/Communicator/Communicator.actions.js
  src/helpers.js
Labels: feature

#1703 Fix/create-remote-Board-on-update-LoadBoards
  src/components/Board/Board.actions.js
  src/components/Board/Board.constants.js
  src/components/Board/Board.container.js
  src/components/Board/Board.reducer.js
Labels: bug

#1731 Save only necessary keys on local userData
  src/components/App/App.constants.js
  src/components/App/App.reducer.js
Labels: bug

#1724 [Snyk] Security upgrade echarts from 5.4.3 to 5.5.1
  package.json
  yarn.lock
Labels: dependencies
